### ISSUE TITLE
docs: misc items

### ISSUE THREAD

**Issue by rndmh3ro** [jetporch/jetporch#19]
## First item

There's a colon after the shell.

```
# playbook1.yml
# not using roles
​
- name: sample playbook
​
  groups:
     - groupA
     - groupB
  
  tasks:
  
     - !shell: 
       cmd: echo hi
  
     - !dnf 
       package: tree
```

should be:

```
# playbook1.yml
# not using roles
​
- name: sample playbook
​
  groups:
     - groupA
     - groupB
  
  tasks:
  
     - !shell
       cmd: echo hi
  
     - !dnf 
       package: tree
```

### URL 

https://www.jetporch.com/playbooks/plays#playbook-syntax

## Second item

When defining a list-variable in different places, the list items get merged all together. This should be clarified in the docs.

### URL 

https://www.jetporch.com/playbooks/using-variables
## Third item

vars-precedence: Documented is "Variables defined in the 'vars' or 'vars_files' keyword of a  always win. " - what I noticed is that vars_files take precende over vars. This should be clarified in the docs.

### URL

https://www.jetporch.com/playbooks/using-variables#variable-precedence
